import { Language, Dossier, DossierStatus, Template, PlaceholderSuggestion } from './types';

export const TRANSLATIONS = {
  [Language.NL]: {
    loginTitle: 'Welkom bij CompromisAI',
    loginSubtitle: 'Log in om door te gaan',
    email: 'E-mailadres',
    password: 'Wachtwoord',
    rememberMe: 'Onthoud mij',
    forgotPassword: 'Wachtwoord vergeten?',
    loginBtn: 'Inloggen',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'Nieuw Compromis',
    newCompromisDesc: 'Begin met het maken van een nieuw verkoopscompromis',
    recentCompromises: 'Recente compromissen',
    viewAll: 'Bekijk alles',
    searchPlaceholder: 'Zoek dossier...',
    step1Title: 'Compromis details',
    step1Desc: 'Geef uw compromis een naam en upload de nodige documenten',
    compName: 'Compromis naam',
    compNamePlaceholder: 'bijv. Appartement Jan Janssens',
    uploadTitle: 'Upload documenten',
    dropzone: 'Sleep bestanden of klik om te uploaden',
    dropzoneSub: 'PDF, DOCX, XLS tot 20MB',
    continue: 'Doorgaan',
    chooseTemplate: 'Kies een template',
    chooseTemplateDesc: 'Selecteer een template of upload uw eigen',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Eigen templates',
    useTemplate: 'Gebruik template',
    aiAssistant: 'AI Assistent',
    aiDesc: 'AI-gestuurde suggesties en validatie',
    suggestions: 'Suggesties',
    apply: 'Toepassen',
    save: 'Opslaan',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'In bewerking',
    highCertainty: 'Hoge zekerheid',
    sectionApprove: 'Goedkeuren',
    logout: 'Uitloggen',
    back: 'Terug',
  },
  [Language.FR]: {
    loginTitle: 'Bienvenue chez CompromisAI',
    loginSubtitle: 'Connectez-vous pour continuer',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    loginBtn: 'Se connecter',
    dashboard: 'Tableau de bord',
    templates: 'Modèles',
    newCompromis: 'Nouveau Compromis',
    newCompromisDesc: 'Commencez à créer un nouveau compromis de vente',
    recentCompromises: 'Compromis récents',
    viewAll: 'Voir tout',
    searchPlaceholder: 'Rechercher un dossier...',
    step1Title: 'Détails du compromis',
    step1Desc: 'Nommez votre compromis et téléchargez les documents nécessaires',
    compName: 'Nom du compromis',
    compNamePlaceholder: 'ex. Appartement Jean Dupont',
    uploadTitle: 'Télécharger des documents',
    dropzone: 'Glissez les fichiers ou cliquez pour télécharger',
    dropzoneSub: 'PDF, DOCX, XLS jusqu\'à 20MB',
    continue: 'Continuer',
    chooseTemplate: 'Choisir un modèle',
    chooseTemplateDesc: 'Sélectionnez un modèle ou téléchargez le vôtre',
    cibTemplates: 'Modèles CIB',
    ownTemplates: 'Propres modèles',
    useTemplate: 'Utiliser le modèle',
    aiAssistant: 'Assistant IA',
    aiDesc: 'Suggestions et validation par IA',
    suggestions: 'Suggestions',
    apply: 'Appliquer',
    save: 'Enregistrer',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'En édition',
    highCertainty: 'Haute certitude',
    sectionApprove: 'Approuver',
    logout: 'Se déconnecter',
    back: 'Retour',
  },
  [Language.EN]: {
    loginTitle: 'Welcome to CompromisAI',
    loginSubtitle: 'Log in to continue',
    email: 'Email address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginBtn: 'Log in',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'New Compromise',
    newCompromisDesc: 'Start creating a new sales compromise',
    recentCompromises: 'Recent compromises',
    viewAll: 'View all',
    searchPlaceholder: 'Search dossier...',
    step1Title: 'Compromise details',
    step1Desc: 'Name your compromise and upload necessary documents',
    compName: 'Compromise name',
    compNamePlaceholder: 'e.g. Apartment John Doe',
    uploadTitle: 'Upload documents',
    dropzone: 'Drag files or click to upload',
    dropzoneSub: 'PDF, DOCX, XLS up to 20MB',
    continue: 'Continue',
    chooseTemplate: 'Choose a template',
    chooseTemplateDesc: 'Select a template or upload your own',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Own templates',
    useTemplate: 'Use template',
    aiAssistant: 'AI Assistant',
    aiDesc: 'AI-driven suggestions and validation',
    suggestions: 'Suggestions',
    apply: 'Apply',
    save: 'Save',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'Editing',
    highCertainty: 'High certainty',
    sectionApprove: 'Approve',
    logout: 'Logout',
    back: 'Back',
  }
};

export const MOCK_DOSSIERS: Dossier[] = [
  {
    id: '1',
    name: 'Appartement Brussels',
    address: 'Kerkstraat 123, 1000 Brussel',
    date: '2025-11-20',
    documentCount: 2,
    status: DossierStatus.DRAFT
  },
  {
    id: '2',
    name: 'Huis Antwerpen',
    address: 'Meir 1, 2000 Antwerpen',
    date: '2025-11-18',
    documentCount: 3,
    status: DossierStatus.COMPLETED
  },
  {
    id: '3',
    name: 'Villa Gent',
    address: 'Veldstraat 40, 9000 Gent',
    date: '2025-11-15',
    documentCount: 5,
    status: DossierStatus.ARCHIVED
  }
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 't1',
    name: 'CIB Huis',
    description: 'Standaard CIB template voor huizen',
    type: 'House',
    source: 'CIB'
  },
  {
    id: 't2',
    name: 'CIB Appartement',
    description: 'Standaard CIB template voor appartementen',
    type: 'Apartment',
    source: 'CIB'
  }
];

export const MOCK_SUGGESTIONS: PlaceholderSuggestion[] = [
  {
    id: 's1',
    label: 'Naam verkoper',
    value: 'Jan Janssens',
    sourceDoc: 'Kadaster.pdf',
    page: 1,
    confidence: 'High'
  },
  {
    id: 's2',
    label: 'Adres pand',
    value: 'Kerkstraat 123, 1000 Brussel',
    sourceDoc: 'EPC.pdf',
    page: 1,
    confidence: 'High'
  },
  {
    id: 's3',
    label: 'EPC Label',
    value: 'B',
    sourceDoc: 'EPC.pdf',
    page: 2,
    confidence: 'High'
  }
];