import { Language, Dossier, DossierStatus, Template, DocumentSection } from './types';

export const TRANSLATIONS = {
  [Language.NL]: {
    loginTitle: 'Welkom bij CompromisAI',
    loginSubtitle: 'Log in om door te gaan',
    email: 'E-mailadres',
    password: 'Wachtwoord',
    rememberMe: 'Onthoud mij',
    forgotPassword: 'Wachtwoord vergeten?',
    loginBtn: 'Inloggen',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'Nieuw Compromis',
    newCompromisDesc: 'Begin met het maken van een nieuw verkoopscompromis',
    recentCompromises: 'Recente compromissen',
    viewAll: 'Bekijk alles',
    searchPlaceholder: 'Zoek dossier...',
    step1Title: 'Compromis details',
    step1Desc: 'Geef uw compromis een naam en upload de nodige documenten',
    compName: 'Compromis naam',
    compNamePlaceholder: 'bijv. Appartement Jan Janssens',
    uploadTitle: 'Upload documenten',
    dropzone: 'Sleep bestanden of klik om te uploaden',
    dropzoneSub: 'PDF, DOCX, XLS tot 20MB',
    continue: 'Doorgaan',
    chooseTemplate: 'Kies een template',
    chooseTemplateDesc: 'Selecteer een template of upload uw eigen',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Eigen templates',
    useTemplate: 'Gebruik template',
    aiAssistant: 'AI Copilot',
    aiDesc: 'AI-gestuurde suggesties en validatie',
    suggestions: 'Suggesties',
    apply: 'Toepassen',
    save: 'Opslaan',
    export: 'Exporteren',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'In bewerking',
    highCertainty: 'Hoge zekerheid',
    sectionApprove: 'Sectie goedkeuren',
    logout: 'Uitloggen',
    back: 'Terug',
    archive: 'Archief',
    archived: 'Gearchiveerd',
    active: 'Actief',
    compare: 'Vergelijk versies',
    archiveDossier: 'Dossier archiveren',
    unarchiveDossier: 'Dossier heropenen',
    timeline: 'Tijdlijn',
    documents: 'Documenten',
    openEdit: 'Open editor',
    source: 'Bron',
    approve: 'Keur goed',
    validationChecklist: 'Validatie Checklist',
    undo: 'Ongedaan maken',
    redo: 'Opnieuw uitvoeren',
    reject: 'Afkeuren',
    addSection: 'Sectie toevoegen',
    generate: 'Genereer Document',
    aiSuggestions: 'Aanbevolen door AI',
    otherTemplates: 'Andere templates',
    remarks: 'Opmerkingen',
    remarksPlaceholder: 'Voeg extra instructies toe voor de AI...',
    warningUnapproved: 'Niet alle elementen zijn goedgekeurd. Weet u zeker dat u wilt doorgaan?',
    classifiedDocs: 'Geclassificeerde Documenten',
    otherDocs: 'Andere documenten',
    missingDocs: 'Ontbrekende documenten',
    settings: 'Instellingen',
    incomplete: 'Onvoltooid',
  },
  [Language.FR]: {
    loginTitle: 'Bienvenue chez CompromisAI',
    loginSubtitle: 'Connectez-vous pour continuer',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    loginBtn: 'Se connecter',
    dashboard: 'Tableau de bord',
    templates: 'Modèles',
    newCompromis: 'Nouveau Compromis',
    newCompromisDesc: 'Commencez à créer un nouveau compromis de vente',
    recentCompromises: 'Compromis récents',
    viewAll: 'Voir tout',
    searchPlaceholder: 'Rechercher un dossier...',
    step1Title: 'Détails du compromis',
    step1Desc: 'Nommez votre compromis et téléchargez les documents nécessaires',
    compName: 'Nom du compromis',
    compNamePlaceholder: 'ex. Appartement Jean Dupont',
    uploadTitle: 'Télécharger des documents',
    dropzone: 'Glissez les fichiers ou cliquez pour télécharger',
    dropzoneSub: 'PDF, DOCX, XLS jusqu\'à 20MB',
    continue: 'Continuer',
    chooseTemplate: 'Choisir un modèle',
    chooseTemplateDesc: 'Sélectionnez un modèle ou téléchargez le vôtre',
    cibTemplates: 'Modèles CIB',
    ownTemplates: 'Propres modèles',
    useTemplate: 'Utiliser le modèle',
    aiAssistant: 'Copilote IA',
    aiDesc: 'Suggestions et validation par IA',
    suggestions: 'Suggestions',
    apply: 'Appliquer',
    save: 'Enregistrer',
    export: 'Exporter',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'En édition',
    highCertainty: 'Haute certitude',
    sectionApprove: 'Approuver la section',
    logout: 'Se déconnecter',
    back: 'Retour',
    archive: 'Archives',
    archived: 'Archivé',
    active: 'Actif',
    compare: 'Comparer les versions',
    archiveDossier: 'Archiver le dossier',
    unarchiveDossier: 'Désarchiver le dossier',
    timeline: 'Chronologie',
    documents: 'Documents',
    openEdit: 'Ouvrir l\'éditeur',
    source: 'Source',
    approve: 'Approuver',
    validationChecklist: 'Liste de validation',
    undo: 'Annuler',
    redo: 'Rétablir',
    reject: 'Rejeter',
    addSection: 'Ajouter une section',
    generate: 'Générer le document',
    aiSuggestions: 'Suggéré par l\'IA',
    otherTemplates: 'Autres modèles',
    remarks: 'Remarques',
    remarksPlaceholder: 'Ajoutez des instructions supplémentaires pour l\'IA...',
    warningUnapproved: 'Tous les éléments ne sont pas approuvés. Voulez-vous vraiment continuer ?',
    classifiedDocs: 'Documents classifiés',
    otherDocs: 'Autres documents',
    missingDocs: 'Documents manquants',
    settings: 'Paramètres',
    incomplete: 'Incomplet',
  },
  [Language.EN]: {
    loginTitle: 'Welcome to CompromisAI',
    loginSubtitle: 'Log in to continue',
    email: 'Email address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginBtn: 'Log in',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'New Compromise',
    newCompromisDesc: 'Start creating a new sales compromise',
    recentCompromises: 'Recent compromises',
    viewAll: 'View all',
    searchPlaceholder: 'Search dossier...',
    step1Title: 'Compromise details',
    step1Desc: 'Name your compromise and upload necessary documents',
    compName: 'Compromise name',
    compNamePlaceholder: 'e.g. Apartment John Doe',
    uploadTitle: 'Upload documents',
    dropzone: 'Drag files or click to upload',
    dropzoneSub: 'PDF, DOCX, XLS up to 20MB',
    continue: 'Continue',
    chooseTemplate: 'Choose a template',
    chooseTemplateDesc: 'Select a template or upload your own',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Own templates',
    useTemplate: 'Use template',
    aiAssistant: 'AI Copilot',
    aiDesc: 'AI-driven suggestions and validation',
    suggestions: 'Suggestions',
    apply: 'Apply',
    save: 'Save',
    export: 'Export',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'Editing',
    highCertainty: 'High certainty',
    sectionApprove: 'Approve Section',
    logout: 'Logout',
    back: 'Back',
    archive: 'Archive',
    archived: 'Archived',
    active: 'Active',
    compare: 'Compare versions',
    archiveDossier: 'Archive dossier',
    unarchiveDossier: 'Unarchive dossier',
    timeline: 'Timeline',
    documents: 'Documents',
    openEdit: 'Open editor',
    source: 'Source',
    approve: 'Approve',
    validationChecklist: 'Validation Checklist',
    undo: 'Undo',
    redo: 'Redo',
    reject: 'Reject',
    addSection: 'Add Section',
    generate: 'Generate Document',
    aiSuggestions: 'AI Suggested',
    otherTemplates: 'Other templates',
    remarks: 'Remarks',
    remarksPlaceholder: 'Add extra instructions for the AI...',
    warningUnapproved: 'Not all elements are approved. Are you sure you want to proceed?',
    classifiedDocs: 'Classified Documents',
    otherDocs: 'Other documents',
    missingDocs: 'Missing documents',
    settings: 'Settings',
    incomplete: 'Incomplete',
  }
};

export const MOCK_DOSSIERS: Dossier[] = [
  {
    id: '1',
    name: 'Appartement Brussels',
    address: 'Kerkstraat 123, 1000 Brussel',
    date: '2025-11-20',
    creationDate: '2025-11-01',
    documentCount: 2,
    status: DossierStatus.DRAFT,
    type: 'Apartment',
    timeline: [
      { id: 't1', date: '2025-11-01', title: 'Dossier aangemaakt', description: 'Initiele creatie', user: 'Jan' },
      { id: 't2', date: '2025-11-02', title: 'Documenten geupload', description: 'EPC en Kadaster toegevoegd', user: 'Jan' },
      { id: 't3', date: '2025-11-20', title: 'Draft v1', description: 'Eerste versie gegenereerd', user: 'AI' },
    ]
  },
  {
    id: '2',
    name: 'Huis Antwerpen',
    address: 'Meir 1, 2000 Antwerpen',
    date: '2025-11-18',
    creationDate: '2025-10-15',
    documentCount: 3,
    status: DossierStatus.COMPLETED,
    type: 'House',
    timeline: []
  },
  {
    id: '3',
    name: 'Villa Gent',
    address: 'Veldstraat 40, 9000 Gent',
    date: '2025-11-15',
    creationDate: '2025-09-01',
    documentCount: 5,
    status: DossierStatus.ARCHIVED,
    type: 'House',
    timeline: []
  },
  {
    id: '4',
    name: 'Studio Leuven',
    address: 'Bondgenotenlaan 55, 3000 Leuven',
    date: '2025-10-01',
    creationDate: '2025-09-20',
    documentCount: 4,
    status: DossierStatus.ARCHIVED,
    type: 'Apartment',
    timeline: []
  }
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 't1',
    name: 'CIB Huis',
    description: 'Standaard CIB template voor huizen',
    type: 'House',
    source: 'CIB',
    isAiSuggested: true
  },
  {
    id: 't2',
    name: 'CIB Appartement',
    description: 'Standaard CIB template voor appartementen',
    type: 'Apartment',
    source: 'CIB',
    isAiSuggested: false
  },
  {
    id: 't3',
    name: 'CIB Handelspand',
    description: 'Standaard CIB template voor commercieel vastgoed',
    type: 'Commercial',
    source: 'CIB',
    isAiSuggested: false
  }
];

export const MOCK_SECTIONS: DocumentSection[] = [
  {
    id: 'sec1',
    title: 'Artikel 1: Partijen',
    content: 'Tussen ondergetekenden:\n\nVERKOPER(S):\nNaam: [placeholder:seller_name]\nAdres: [placeholder:seller_address]\n\nKOPER(S):\nNaam: [placeholder:buyer_name]',
    isApproved: false,
    placeholders: [
      { id: 'p1', label: 'Naam verkoper', currentValue: 'Jan Janssens', sourceDoc: 'Kadaster.pdf', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'p2', label: 'Adres verkoper', currentValue: 'Dorpsstraat 1, 9000 Gent', sourceDoc: 'Identiteitskaart.pdf', sourcePage: 1, confidence: 'High', isApproved: true },
      { id: 'p3', label: 'Naam koper', currentValue: 'Piet Peters', sourceDoc: 'Email_bod.pdf', sourcePage: 1, confidence: 'Medium', isApproved: false },
    ]
  },
  {
    id: 'sec2',
    title: 'Artikel 2: Object',
    content: 'De verkoper verklaart te verkopen aan de koper, die aanvaardt:\nEen woonhuis gelegen te [placeholder:prop_address].\nEPC Score: [placeholder:epc_score].',
    isApproved: true,
    placeholders: [
      { id: 'p4', label: 'Adres pand', currentValue: 'Kerkstraat 123, 1000 Brussel', sourceDoc: 'EPC.pdf', sourcePage: 1, confidence: 'High', isApproved: true },
      { id: 'p5', label: 'EPC Score', currentValue: 'B', sourceDoc: 'EPC.pdf', sourcePage: 2, confidence: 'High', isApproved: true },
    ]
  }
];