import { Language, Dossier, DossierStatus, Template, DocumentSection } from './types';

export const SUPPORTED_PLACEHOLDERS = [
  { id: 'seller_firstname', label: 'Voornaam verkoper' },
  { id: 'seller_lastname', label: 'Achternaam verkoper' },
  { id: 'seller_birthplace', label: 'Geboorteplaats verkoper' },
  { id: 'seller_birthdate', label: 'Geboortedatum verkoper' },
  { id: 'seller_address', label: 'Adres verkoper' },
  { id: 'buyer1_firstname', label: 'Voornaam koper 1' },
  { id: 'buyer1_lastname', label: 'Achternaam koper 1' },
  { id: 'buyer1_birthplace', label: 'Geboorteplaats koper 1' },
  { id: 'buyer1_birthdate', label: 'Geboortedatum koper 1' },
  { id: 'buyer2_firstname', label: 'Voornaam koper 2' },
  { id: 'buyer2_lastname', label: 'Achternaam koper 2' },
  { id: 'buyer2_birthplace', label: 'Geboorteplaats koper 2' },
  { id: 'buyer2_birthdate', label: 'Geboortedatum koper 2' },
  { id: 'buyers_address', label: 'Adres kopers' },
  { id: 'property_municipality', label: 'Gemeente eigendom' },
  { id: 'property_section', label: 'Kadastrale afdeling' },
  { id: 'property_street', label: 'Straat eigendom' },
  { id: 'cadastral_number', label: 'Kadastraal nummer' },
  { id: 'sale_price_amount', label: 'Verkoopprijs' },
  { id: 'deposit_amount', label: 'Voorschot' },
  { id: 'notary_name', label: 'Naam notaris' },
  { id: 'signing_date', label: 'Datum ondertekening' },
  { id: 'signing_location', label: 'Plaats ondertekening' },
];

export const TRANSLATIONS = {
  [Language.NL]: {
    loginTitle: 'Welkom bij compromAIs',
    loginSubtitle: 'Log in om door te gaan',
    email: 'E-mailadres',
    password: 'Wachtwoord',
    rememberMe: 'Onthoud mij',
    forgotPassword: 'Wachtwoord vergeten?',
    loginBtn: 'Inloggen',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'Nieuw Dossier',
    newCompromisDesc: 'Begin met het maken van een nieuw dossier',
    recentCompromises: 'Recente compromissen',
    viewAll: 'Bekijk alles',
    searchPlaceholder: 'Zoek dossier...',
    step1Title: 'Compromis details',
    step1Desc: 'Geef uw compromis een naam en upload de nodige documenten',
    compName: 'Compromis naam',
    compNamePlaceholder: 'bijv. Appartement Jan Janssens',
    uploadTitle: 'Upload documenten',
    dropzone: 'Sleep bestanden of klik om te uploaden',
    dropzoneSub: 'PDF, DOCX, XLS tot 20MB',
    continue: 'Doorgaan',
    chooseTemplate: 'Kies een template',
    chooseTemplateDesc: 'Selecteer een template of upload uw eigen',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Eigen templates',
    useTemplate: 'Gebruik template',
    aiAssistant: 'AI Copilot',
    aiDesc: 'AI-gestuurde suggesties en validatie',
    suggestions: 'Suggesties',
    apply: 'Toepassen',
    save: 'Opslaan',
    export: 'Exporteren',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'In bewerking',
    highCertainty: 'Hoge zekerheid',
    sectionApprove: 'Sectie goedkeuren',
    logout: 'Uitloggen',
    back: 'Terug',
    archive: 'Archief',
    archived: 'Gearchiveerd',
    active: 'Actief',
    compare: 'Vergelijk versies',
    archiveDossier: 'Dossier archiveren',
    unarchiveDossier: 'Dossier heropenen',
    timeline: 'Tijdlijn',
    documents: 'Documenten',
    openEdit: 'Open editor',
    source: 'Bron',
    approve: 'Keur goed',
    validationChecklist: 'Validatie Checklist',
    undo: 'Ongedaan maken',
    redo: 'Opnieuw uitvoeren',
    reject: 'Afkeuren',
    addSection: 'Sectie toevoegen',
    generate: 'Genereer Document',
    aiSuggestions: 'Aanbevolen door AI',
    otherTemplates: 'Andere templates',
    remarks: 'Opmerkingen',
    remarksPlaceholder: 'Voeg extra instructies toe voor de AI...',
    warningUnapproved: 'Niet alle elementen zijn goedgekeurd. Weet u zeker dat u wilt doorgaan?',
    classifiedDocs: 'Geclassificeerde Documenten',
    otherDocs: 'Andere documenten',
    missingDocs: 'Ontbrekende documenten',
    settings: 'Instellingen',
    incomplete: 'In behandeling',
    uploadSubtitle: 'Upload documenten en kies een template om te starten.',
    uploadedFiles: 'Geüploade Bestanden',
    aiSuggestionText: 'Op basis van de geüploade documenten raden we',
    aiSuggestionTextEnd: 'aan.',
    recommended: 'AANBEVOLEN',
    optional: 'Optioneel',
    generateDescription: 'De AI zal de geüploade documenten analyseren en automatisch invullen in het gekozen sjabloon.',
    documentChecklist: 'Document Checklist',
    justNow: 'Zonet',
    dossierCreated: 'Dossier Aangemaakt',
    dossierInitialized: 'Dossier geïnitialiseerd met templates.',
    you: 'U',
    aiWorking: 'AI is aan het werk...',
    uploadingDocs: 'Documenten uploaden...',
    analyzingContent: 'Inhoud analyseren...',
    extractingData: 'Gegevens extraheren...',
    finalizingCompromise: 'Compromis genereren...',
    draft: 'Concept',
    completed: 'Voltooid',
    noActiveDossiers: 'Geen actieve dossiers.',
    noArchivedDossiers: 'Geen gearchiveerde dossiers.',
    deleteDossier: 'Dossier verwijderen',
    deleteConfirmation: 'Ben je zeker dat je dit wilt verwijderen?',
    dontShowAgain: 'Dit niet meer tonen',
    confirmDelete: 'Verwijderen',
    settingsDeleteConfirmation: 'Toon bevestigingspop-up bij verwijderen van een dossier',
    settingsDeleteVersionConfirmation: 'Toon bevestigingspop-up bij verwijderen van een versie',
    settingsDeleteAgreementConfirmation: 'Toon bevestigingspop-up bij verwijderen van een overeenkomst',
    deleteVersion: 'Versie verwijderen',
    deleteVersionConfirmation: 'Ben je zeker dat je deze versie wilt verwijderen?',
    cancel: 'Annuleren',
    myAccount: 'Mijn Account',
    accountDetails: 'Accountgegevens',
    userName: 'Naam',
    userEmail: 'E-mailadres',
    welcomeBack: 'Welkom terug! Log in op uw account.',
    registerBroker: 'Maak een nieuw account aan als makelaar.',
    loginCib: 'Log in met CIB',
    devLogin: 'Dev Login',
    noAccount: 'Nog geen account? Registreer hier',
    fullName: 'Volledige Naam',
    backToLogin: 'Terug naar Login',
    registerAccount: 'Registreer account',
    aiConnected: 'AI Verbonden',
    aiDisconnected: 'AI Niet Verbonden',
    aiChecking: 'AI Status Controleren...',
    themeToggle: 'Thema wisselen',
    myDivision: 'Mijn opdeling',
    recentlyOpened: 'Recent gebruikt',
    recent: 'Recent',
    dragToConcept: 'Sleep hier dossiers naartoe om ze naar Concept te verplaatsen',
    dragToActive: 'Sleep hier dossiers naartoe om ze naar In Behandeling te verplaatsen',
    dragToArchive: 'Sleep hier dossiers naartoe om te archiveren',
    privacySecurity: 'Privacy & Veiligheid',
    aiSettings: 'AI Verrijking (Advanced)',
    docPromptLabel: 'Document Analyse Verrijking',
    docPromptDesc: "Wordt gebruikt bij het scannen van dossiers (ID's, aktes, etc.). Bijvoorbeeld: 'Focus vooral op de namen van de kopers' of 'Formatteer data altijd als DD-MM-YYYY'.",
    docPromptPlaceholder: 'Typ hier je extra instructies voor data extractie...',
    tplPromptLabel: 'Template Analyse Verrijking',
    tplPromptDesc: 'Wordt gebruikt bij het analyseren van nieuwe PDF sjablonen. Bijvoorbeeld: "Maak voor elk lidwoord een aparte placeholder" of "Groepeer alle adressen in één sectie".',
    tplPromptPlaceholder: 'Typ hier je extra instructies voor sjabloon analyse...',
    notifications: 'Notificaties',
    comingSoon: 'Binnenkort beschikbaar',
    displayOptions: 'Weergave',
    showAiStatusSetting: 'Toon AI Status Indicator',
    showAiStatusDesc: 'Toon een visuele indicator in de zijbalk die de status van de AI-verbinding weergeeft.',
    noArchivedFound: 'Geen gearchiveerde dossiers gevonden.',
    dossierDetails: 'Dossier Details & Bestanden',
    startDossier: 'Start Dossier',
    creatingDossier: 'Dossier aanmaken...',
    dossierBeingCreated: 'Dossier wordt aangemaakt.',
    dossierCreateError: 'Er ging iets mis bij het aanmaken van het dossier. Probeer het opnieuw.',
    deleteDossierError: 'Kon dossier niet verwijderen.',
    deleteAgreement: 'Overeenkomst verwijderen',
    deleteAgreementConfirmation: 'Ben je zeker dat je deze overeenkomst wilt verwijderen?',
    renameVersion: 'Hernoem versie',
    versionRenamePopupTitle: 'Versie hernoemen',
    versionRenameNewName: 'Nieuwe naam voor versie',
    versionRenamePlaceholder: 'Bijv. Concept v2, Finale Versie...',
    customAgreement: 'Zelfgeschreven Overeenkomst',
    addVersionTooltip: 'Versie toevoegen',
    noAgreementsFound: 'Geen verkoopovereenkomsten gevonden.',
    startNewAgreement: 'Nieuwe verkoopovereenkomst starten',
    noActivitiesYet: 'Nog geen activiteiten.',
    details: 'Details',
    creationDate: 'Creatie datum',
    noDocumentsUploaded: 'Nog geen documenten geüpload.',
    addVersionModalTitle: 'Nieuwe Versie Toevoegen',
    addVersionModalSub: 'Hoe wilt u de nieuwe versie aanmaken?',
    uploadFile: 'Bestand uploaden',
    uploadFileDesc: 'Upload een extern PDF of Word document',
    copyCurrentVersion: 'Huidige versie kopiëren',
    copyVersionDesc: 'Start een nieuwe draft op basis van de laatste versie',
    startNewAgreementTitle: 'Start Nieuwe Overeenkomst',
    chooseTemplateStart: 'Kies een template om mee te beginnen',
    documentPreview: 'Document Preview',
    selectDocumentToView: 'Selecteer een document om te bekijken',
    deleteSectionConfirm: 'Verwijder deze sectie?',
    addSectionBtn: 'Voeg nieuwe sectie toe',
    sourceIdCard: 'Bron: Identiteitskaart.jpg',
    sourceDocument: 'Bron Document',
    openInBrowser: 'Open in browser',
    documentLoading: 'Document laden...',
    documentLoadError: 'Fout bij laden van document.',
    aiContextMapping: 'AI Context Mapping',
    aiContextFieldContent: 'Inhoud van veld',
    aiContextMatchingId: 'overeenkomstig met ID scan.',
    foundData: 'Gevonden Data',
    noSourceFound: '[ Geen bron gevonden ]',
    percentComplete: '% Compleet',
    moveToConcept: 'Verplaats naar Concept',
    moveToActive: 'Verplaats naar In Behandeling',
    moveTo: 'Verplaats naar',
    statusApproved: 'Goedgekeurd',
    statusForReview: 'Ter controle',
    manageTemplatesDesc: 'Beheer uw document sjablonen en extractie regels',
    newTemplateBtn: 'Nieuwe Template',
    tabAll: 'Alle',
    tabCib: 'CIB',
    tabCustom: 'Eigen',
    tabArchived: 'Gearchiveerd',
    searchTemplatesPlaceholder: 'Zoek templates...',
    cibOfficialBadge: 'CIB Official',
    customTemplateBadge: 'Eigen Template',
    deleteAction: 'Verwijderen',
    archiveAction: 'Archiveren',
    unarchiveAction: 'Dearchiveren',
    addTemplateCard: 'Template Toevoegen',
    templateNamePlaceholder: 'Template Naam',
    descriptionPlaceholder: 'Beschrijving',
    templateTitlePlaceholder: 'Voer de titel van het document in...',
    sectionContentPlaceholder: 'Voer hier de sectie-inhoud in...',
    choosePlaceholder: 'Kies een placeholder',
    noMatchingPlaceholders: 'Geen overeenkomende placeholders...',
    noContentAvailable: 'Geen inhoud beschikbaar om te bekijken of te bewerken.',
    addSectionBtnTemplate: 'Sectie Toevoegen',
    closeBtn: 'Sluiten',
    newNameLabel: 'Naam',
    newNamePlaceholder: 'bijv. Mijn Eigen Huis Template',
    newDescLabel: 'Beschrijving',
    newDescPlaceholder: 'Geef een korte beschrijving...',
    newTypeLabel: 'Type',
    startFromFileLabel: 'Of start vanaf een PDF of Word bestand (AI Analyse)',
    geminiAnalysisDesc: 'Gemini zal het bestand analyseren tijdens het opslaan om secties en placeholders te identificeren.',
    analyzingSavingBtn: 'Bezig met analyseren & opslaan...',
    saveTemplateBtn: 'Template Opslaan',
    deleteTemplateTitle: 'Template verwijderen?',
    deleteTemplateDescPart1: 'Weet u zeker dat u de template "',
    deleteTemplateDescPart2: '" wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
    yesDeleteBtn: 'Ja, Verwijder',
    changesSavedToast: 'Wijzigingen succesvol opgeslagen',
    editBtn: 'Bewerken',
    templateNameExists: 'De naam van deze template bestaat al. Kies een andere naam.',
  },
  [Language.FR]: {
    loginTitle: 'Bienvenue chez compromAIs',
    loginSubtitle: 'Connectez-vous pour continuer',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    loginBtn: 'Se connecter',
    dashboard: 'Tableau de bord',
    templates: 'Modèles',
    newCompromis: 'Nouveau Compromis',
    newCompromisDesc: 'Commencez à créer un nouveau compromis de vente',
    recentCompromises: 'Compromis récents',
    viewAll: 'Voir tout',
    searchPlaceholder: 'Rechercher un dossier...',
    step1Title: 'Détails du compromis',
    step1Desc: 'Nommez votre compromis et téléchargez les documents nécessaires',
    compName: 'Nom du compromis',
    compNamePlaceholder: 'ex. Appartement Jean Dupont',
    uploadTitle: 'Télécharger des documents',
    dropzone: 'Glissez les fichiers ou cliquez pour télécharger',
    dropzoneSub: 'PDF, DOCX, XLS jusqu\'à 20MB',
    continue: 'Continuer',
    chooseTemplate: 'Choisir un modèle',
    chooseTemplateDesc: 'Sélectionnez un modèle ou téléchargez le vôtre',
    cibTemplates: 'Modèles CIB',
    ownTemplates: 'Propres modèles',
    useTemplate: 'Utiliser le modèle',
    aiAssistant: 'Copilote IA',
    aiDesc: 'Suggestions et validation par IA',
    suggestions: 'Suggestions',
    apply: 'Appliquer',
    save: 'Enregistrer',
    export: 'Exporter',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'En édition',
    highCertainty: 'Haute certitude',
    sectionApprove: 'Approuver la section',
    logout: 'Se déconnecter',
    back: 'Retour',
    archive: 'Archives',
    archived: 'Archivé',
    active: 'Actif',
    compare: 'Comparer les versions',
    archiveDossier: 'Archiver le dossier',
    unarchiveDossier: 'Désarchiver le dossier',
    timeline: 'Chronologie',
    documents: 'Documents',
    openEdit: 'Ouvrir l\'éditeur',
    source: 'Source',
    approve: 'Approuver',
    validationChecklist: 'Liste de validation',
    undo: 'Annuler',
    redo: 'Rétablir',
    reject: 'Rejeter',
    addSection: 'Ajouter une section',
    generate: 'Générer le document',
    aiSuggestions: 'Suggéré par l\'IA',
    otherTemplates: 'Autres modèles',
    remarks: 'Remarques',
    remarksPlaceholder: 'Ajoutez des instructions supplémentaires pour l\'IA...',
    warningUnapproved: 'Tous les éléments ne sont pas approuvés. Voulez-vous vraiment continuer ?',
    classifiedDocs: 'Documents classifiés',
    otherDocs: 'Autres documents',
    missingDocs: 'Documents manquants',
    settings: 'Paramètres',
    incomplete: 'Incomplet',
    uploadSubtitle: 'Téléchargez des documents et choisissez un modèle pour commencer.',
    uploadedFiles: 'Fichiers téléchargés',
    aiSuggestionText: 'Sur la base des documents téléchargés, nous recommandons',
    aiSuggestionTextEnd: '.',
    recommended: 'RECOMMANDÉ',
    optional: 'Optionnel',
    generateDescription: 'L\'IA analysera les documents téléchargés et les remplira automatiquement dans le modèle choisi.',
    documentChecklist: 'Liste de contrôle des documents',
    justNow: 'À l\'instant',
    dossierCreated: 'Dossier créé',
    dossierInitialized: 'Dossier initialisé avec des modèles.',
    you: 'Vous',
    aiWorking: 'L\'IA est au travail...',
    uploadingDocs: 'Téléchargement des documents...',
    analyzingContent: 'Analyse du contenu...',
    extractingData: 'Extraction des données...',
    finalizingCompromise: 'Finalisation du compromis...',
    draft: 'Brouillon',
    completed: 'Terminé',
    noActiveDossiers: 'Aucun dossier actif.',
    noArchivedDossiers: 'Aucun dossier archivé.',
    deleteDossier: 'Supprimer le dossier',
    deleteConfirmation: 'Êtes-vous sûr de vouloir supprimer ceci ?',
    dontShowAgain: 'Ne plus afficher',
    confirmDelete: 'Supprimer',
    settingsDeleteConfirmation: 'Afficher la confirmation de suppression',
    deleteVersion: 'Supprimer la version',
    deleteVersionConfirmation: 'Êtes-vous sûr de vouloir supprimer cette version ?',
    cancel: 'Annuler',
    myAccount: 'Mon Compte',
    accountDetails: 'Détails du Compte',
    userName: 'Nom',
    userEmail: 'Adresse e-mail',
    welcomeBack: 'Bon retour ! Connectez-vous à votre compte.',
    registerBroker: 'Créez un nouveau compte en tant que courtier.',
    loginCib: 'Se connecter avec CIB',
    devLogin: 'Connexion développeur',
    noAccount: 'Pas encore de compte ? Inscrivez-vous ici',
    fullName: 'Nom Complet',
    backToLogin: 'Retour à la connexion',
    registerAccount: 'Enregistrer le compte',
    aiConnected: 'IA Connectée',
    aiDisconnected: 'IA Non connectée',
    aiChecking: 'Vérification du statut IA...',
    themeToggle: 'Changer de thème',
    myDivision: 'Ma division',
    recentlyOpened: 'Récemment utilisé',
    recent: 'Récent',
    dragToConcept: 'Faites glisser les dossiers ici pour les déplacer vers Brouillon',
    dragToActive: 'Faites glisser les dossiers ici pour les déplacer vers En Traitement',
    dragToArchive: 'Faites glisser les dossiers ici pour archiver',
    privacySecurity: 'Confidentialité & Sécurité',
    aiSettings: 'Enrichissement IA (Avancé)',
    docPromptLabel: "Enrichissement d'analyse de document",
    docPromptDesc: 'Utilisé lors de la numérisation des dossiers. Par exemple : "Concentrez-vous sur les noms des acheteurs" ou "Formatez les dates en JJ-MM-AAAA".',
    docPromptPlaceholder: 'Tapez vos instructions supplémentaires ici...',
    tplPromptLabel: "Enrichissement d'analyse de modèle",
    tplPromptDesc: "Utilisé lors de l'analyse de nouveaux modèles PDF.",
    tplPromptPlaceholder: 'Tapez vos instructions supplémentaires pour le modèle ici...',
    notifications: 'Notifications',
    comingSoon: 'Bientôt disponible',
    displayOptions: 'Affichage',
    showAiStatusSetting: "Afficher l'indicateur de statut IA",
    showAiStatusDesc: 'Afficher un indicateur visuel dans la barre latérale.',
    noArchivedFound: 'Aucun dossier archivé trouvé.',
    dossierDetails: 'Détails du dossier et fichiers',
    startDossier: 'Démarrer le dossier',
    creatingDossier: 'Création du dossier...',
    dossierBeingCreated: 'Le dossier est en cours de création.',
    dossierCreateError: 'Une erreur est survenue lors de la création du dossier. Veuillez réessayer.',
    deleteDossierError: 'Impossible de supprimer le dossier.',
    deleteAgreement: 'Supprimer l\'accord',
    deleteAgreementConfirmation: 'Êtes-vous sûr de vouloir supprimer cet accord ?',
    renameVersion: 'Renommer la version',
    versionRenamePopupTitle: 'Renommer la version',
    versionRenameNewName: 'Nouveau nom pour la version',
    versionRenamePlaceholder: 'Ex. Brouillon v2, Version Finale...',
    customAgreement: 'Accord écrit sur mesure',
    addVersionTooltip: 'Ajouter une version',
    noAgreementsFound: 'Aucun accord de vente trouvé.',
    startNewAgreement: 'Commencer un nouvel accord de vente',
    noActivitiesYet: 'Aucune activité pour le moment.',
    details: 'Détails',
    creationDate: 'Date de création',
    noDocumentsUploaded: 'Aucun document téléchargé.',
    addVersionModalTitle: 'Ajouter une nouvelle version',
    addVersionModalSub: 'Comment voulez-vous créer la nouvelle version ?',
    uploadFile: 'Télécharger un fichier',
    uploadFileDesc: 'Téléchargez un document PDF ou Word externe',
    copyCurrentVersion: 'Copier la version actuelle',
    copyVersionDesc: 'Commencez un nouveau brouillon basé sur la dernière version',
    startNewAgreementTitle: 'Démarrer un nouvel accord',
    chooseTemplateStart: 'Choisissez un modèle pour commencer',
    documentPreview: 'Aperçu du document',
    selectDocumentToView: 'Sélectionnez un document à afficher',
    deleteSectionConfirm: 'Supprimer cette section ?',
    addSectionBtn: 'Ajouter une nouvelle section',
    sourceIdCard: 'Source : Carte d\'identité.jpg',
    sourceDocument: 'Document source',
    openInBrowser: 'Ouvrir dans le navigateur',
    documentLoading: 'Chargement du document...',
    documentLoadError: 'Erreur lors du chargement du document.',
    aiContextMapping: 'Mappage de contexte IA',
    aiContextFieldContent: 'Contenu du champ',
    aiContextMatchingId: 'correspondant au scan ID.',
    foundData: 'Données trouvées',
    noSourceFound: '[ Aucune source trouvée ]',
    percentComplete: '% Complet',
    moveToConcept: 'Déplacer vers Brouillon',
    moveToActive: 'Déplacer vers En traitement',
    moveTo: 'Déplacer vers',
    statusApproved: 'Approuvé',
    statusForReview: 'À vérifier',
    manageTemplatesDesc: 'Gérez vos modèles de documents et vos règles d\'extraction',
    newTemplateBtn: 'Nouveau Modèle',
    tabAll: 'Tous',
    tabCib: 'CIB',
    tabCustom: 'Propres',
    tabArchived: 'Archivés',
    searchTemplatesPlaceholder: 'Rechercher des modèles...',
    cibOfficialBadge: 'CIB Officiel',
    customTemplateBadge: 'Propre Modèle',
    deleteAction: 'Supprimer',
    archiveAction: 'Archiver',
    unarchiveAction: 'Désarchiver',
    addTemplateCard: 'Ajouter un Modèle',
    templateNamePlaceholder: 'Nom du Modèle',
    descriptionPlaceholder: 'Description',
    templateTitlePlaceholder: 'Entrez le titre du document...',
    sectionContentPlaceholder: 'Entrez le contenu de la section ici...',
    choosePlaceholder: 'Choisissez un espace réservé',
    noMatchingPlaceholders: 'Aucun espace réservé correspondant...',
    noContentAvailable: 'Aucun contenu disponible pour l\'aperçu ou l\'édition.',
    addSectionBtnTemplate: 'Ajouter une Section',
    closeBtn: 'Fermer',
    newNameLabel: 'Nom',
    newNamePlaceholder: 'ex. Mon propre modèle de maison',
    newDescLabel: 'Description',
    newDescPlaceholder: 'Donnez une courte description...',
    newTypeLabel: 'Type',
    startFromFileLabel: 'Ou commencez à partir d\'un fichier PDF ou Word (Analyse IA)',
    geminiAnalysisDesc: 'Gemini analysera le fichier lors de la sauvegarde pour identifier les sections et les espaces réservés.',
    analyzingSavingBtn: 'Analyse et sauvegarde en cours...',
    saveTemplateBtn: 'Sauvegarder le Modèle',
    deleteTemplateTitle: 'Supprimer le modèle ?',
    deleteTemplateDescPart1: 'Êtes-vous sûr de vouloir supprimer le modèle "',
    deleteTemplateDescPart2: '" ? Cette action ne peut pas être annulée.',
    yesDeleteBtn: 'Oui, Supprimer',
    changesSavedToast: 'Modifications enregistrées avec succès',
    editBtn: 'Éditer',
    templateNameExists: 'Le nom de ce modèle existe déjà. Veuillez choisir un autre nom.',
  },
  [Language.EN]: {
    loginTitle: 'Welcome to CompromisAI',
    loginSubtitle: 'Log in to continue',
    email: 'Email address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginBtn: 'Log in',
    dashboard: 'Dashboard',
    templates: 'Templates',
    newCompromis: 'New Compromise',
    newCompromisDesc: 'Start creating a new sales compromise',
    recentCompromises: 'Recent compromises',
    viewAll: 'View all',
    searchPlaceholder: 'Search dossier...',
    step1Title: 'Compromise details',
    step1Desc: 'Name your compromise and upload necessary documents',
    compName: 'Compromise name',
    compNamePlaceholder: 'e.g. Apartment John Doe',
    uploadTitle: 'Upload documents',
    dropzone: 'Drag files or click to upload',
    dropzoneSub: 'PDF, DOCX, XLS up to 20MB',
    continue: 'Continue',
    chooseTemplate: 'Choose a template',
    chooseTemplateDesc: 'Select a template or upload your own',
    cibTemplates: 'CIB Templates',
    ownTemplates: 'Own templates',
    useTemplate: 'Use template',
    aiAssistant: 'AI Copilot',
    aiDesc: 'AI-driven suggestions and validation',
    suggestions: 'Suggestions',
    apply: 'Apply',
    save: 'Save',
    export: 'Export',
    exportPdf: 'PDF',
    exportWord: 'Word',
    editing: 'Editing',
    highCertainty: 'High certainty',
    sectionApprove: 'Approve Section',
    logout: 'Logout',
    back: 'Back',
    archive: 'Archive',
    archived: 'Archived',
    active: 'Active',
    compare: 'Compare versions',
    archiveDossier: 'Archive dossier',
    unarchiveDossier: 'Unarchive dossier',
    timeline: 'Timeline',
    documents: 'Documents',
    openEdit: 'Open editor',
    source: 'Source',
    approve: 'Approve',
    validationChecklist: 'Validation Checklist',
    undo: 'Undo',
    redo: 'Redo',
    reject: 'Reject',
    addSection: 'Add Section',
    generate: 'Generate Document',
    aiSuggestions: 'AI Suggested',
    otherTemplates: 'Other templates',
    remarks: 'Remarks',
    remarksPlaceholder: 'Add extra instructions for the AI...',
    warningUnapproved: 'Not all elements are approved. Are you sure you want to proceed?',
    classifiedDocs: 'Classified Documents',
    otherDocs: 'Other documents',
    missingDocs: 'Missing documents',
    settings: 'Settings',
    incomplete: 'Incomplete',
    uploadSubtitle: 'Upload documents and choose a template to get started.',
    uploadedFiles: 'Uploaded Files',
    aiSuggestionText: 'Based on the uploaded documents, we recommend',
    aiSuggestionTextEnd: '.',
    recommended: 'RECOMMENDED',
    optional: 'Optional',
    generateDescription: 'The AI will analyze the uploaded documents and automatically fill them into the chosen template.',
    documentChecklist: 'Document Checklist',
    justNow: 'Just now',
    dossierCreated: 'Dossier Created',
    dossierInitialized: 'Dossier initialized with templates.',
    you: 'You',
    aiWorking: 'AI is working...',
    uploadingDocs: 'Uploading documents...',
    analyzingContent: 'Analyzing content...',
    extractingData: 'Extracting data points...',
    finalizingCompromise: 'Finalizing compromise...',
    draft: 'Draft',
    completed: 'Completed',
    noActiveDossiers: 'No active dossiers.',
    noArchivedDossiers: 'No archived dossiers.',
    deleteDossier: 'Delete dossier',
    deleteConfirmation: 'Are you sure you want to delete this?',
    dontShowAgain: 'Don\'t show again',
    confirmDelete: 'Delete',
    settingsDeleteConfirmation: 'Show delete confirmation popup',
    cancel: 'Cancel',
    myAccount: 'My Account',
    accountDetails: 'Account Details',
    userName: 'Name',
    userEmail: 'Email',
    welcomeBack: 'Welcome back! Log in to your account.',
    registerBroker: 'Create a new account as a broker.',
    loginCib: 'Log in with CIB',
    devLogin: 'Dev Login',
    noAccount: 'No account yet? Register here',
    fullName: 'Full Name',
    backToLogin: 'Back to Login',
    registerAccount: 'Register account',
    aiConnected: 'AI Connected',
    aiDisconnected: 'AI Disconnected',
    aiChecking: 'Checking AI Status...',
    themeToggle: 'Toggle Theme',
    myDivision: 'My division',
    recentlyOpened: 'Recently used',
    recent: 'Recent',
    dragToConcept: 'Drag dossiers here to move them to Draft',
    dragToActive: 'Drag dossiers here to move them to In Progress',
    dragToArchive: 'Drag dossiers here to archive',
    privacySecurity: 'Privacy & Security',
    aiSettings: 'AI Enrichment (Advanced)',
    docPromptLabel: 'Document Analysis Enrichment',
    docPromptDesc: 'Used when scanning dossiers. For example: "Focus especially on buyer names" or "Always format data as DD-MM-YYYY".',
    docPromptPlaceholder: 'Type your extra instructions for extraction here...',
    tplPromptLabel: 'Template Analysis Enrichment',
    tplPromptDesc: 'Used when analyzing new PDF templates.',
    tplPromptPlaceholder: 'Type your extra instructions for template analysis here...',
    notifications: 'Notifications',
    comingSoon: 'Coming soon',
    displayOptions: 'Display',
    showAiStatusSetting: 'Show AI Status Indicator',
    showAiStatusDesc: 'Show a visual indicator in the sidebar showing the status of the AI connection.',
    noArchivedFound: 'No archived dossiers found.',
    dossierDetails: 'Dossier Details & Files',
    startDossier: 'Start Dossier',
    creatingDossier: 'Creating dossier...',
    dossierBeingCreated: 'Dossier is being created.',
    dossierCreateError: 'Something went wrong while creating the dossier. Please try again.',
    deleteDossierError: 'Could not delete dossier.',
    deleteAgreement: 'Delete agreement',
    deleteAgreementConfirmation: 'Are you sure you want to delete this agreement?',
    renameVersion: 'Rename version',
    versionRenamePopupTitle: 'Rename version',
    versionRenameNewName: 'New name for version',
    versionRenamePlaceholder: 'E.g. Draft v2, Final Version...',
    customAgreement: 'Custom Agreement',
    addVersionTooltip: 'Add version',
    noAgreementsFound: 'No sales agreements found.',
    startNewAgreement: 'Start new sales agreement',
    noActivitiesYet: 'No activities yet.',
    details: 'Details',
    creationDate: 'Creation date',
    noDocumentsUploaded: 'No documents uploaded yet.',
    addVersionModalTitle: 'Add New Version',
    addVersionModalSub: 'How do you want to create the new version?',
    uploadFile: 'Upload file',
    uploadFileDesc: 'Upload an external PDF or Word document',
    copyCurrentVersion: 'Copy current version',
    copyVersionDesc: 'Start a new draft based on the latest version',
    startNewAgreementTitle: 'Start New Agreement',
    chooseTemplateStart: 'Choose a template to get started',
    documentPreview: 'Document Preview',
    selectDocumentToView: 'Select a document to view',
    deleteSectionConfirm: 'Delete this section?',
    addSectionBtn: 'Add new section',
    sourceIdCard: 'Source: ID Card.jpg',
    sourceDocument: 'Source Document',
    openInBrowser: 'Open in browser',
    documentLoading: 'Loading document...',
    documentLoadError: 'Error loading document.',
    aiContextMapping: 'AI Context Mapping',
    aiContextFieldContent: 'Content of field',
    aiContextMatchingId: 'matching with ID scan.',
    foundData: 'Found Data',
    noSourceFound: '[ No source found ]',
    percentComplete: '% Complete',
    moveToConcept: 'Move to Draft',
    moveToActive: 'Move to In Progress',
    moveTo: 'Move to',
    statusApproved: 'Approved',
    statusForReview: 'For review',
    manageTemplatesDesc: 'Manage your document templates and extraction rules',
    newTemplateBtn: 'New Template',
    tabAll: 'All',
    tabCib: 'CIB',
    tabCustom: 'Own',
    tabArchived: 'Archived',
    searchTemplatesPlaceholder: 'Search templates...',
    cibOfficialBadge: 'CIB Official',
    customTemplateBadge: 'Own Template',
    deleteAction: 'Delete',
    archiveAction: 'Archive',
    unarchiveAction: 'Unarchive',
    addTemplateCard: 'Add Template',
    templateNamePlaceholder: 'Template Name',
    descriptionPlaceholder: 'Description',
    templateTitlePlaceholder: 'Enter document title...',
    sectionContentPlaceholder: 'Enter section content here...',
    choosePlaceholder: 'Choose a placeholder',
    noMatchingPlaceholders: 'No matching placeholders...',
    noContentAvailable: 'No content available to preview or edit.',
    addSectionBtnTemplate: 'Add Section',
    closeBtn: 'Close',
    newNameLabel: 'Name',
    newNamePlaceholder: 'e.g. My Own House Template',
    newDescLabel: 'Description',
    newDescPlaceholder: 'Provide a short description...',
    newTypeLabel: 'Type',
    startFromFileLabel: 'Or start from a PDF or Word file (AI Analysis)',
    geminiAnalysisDesc: 'Gemini will analyze the file upon saving to identify sections and placeholders.',
    analyzingSavingBtn: 'Analyzing & saving...',
    saveTemplateBtn: 'Save Template',
    deleteTemplateTitle: 'Delete template?',
    deleteTemplateDescPart1: 'Are you sure you want to delete template "',
    deleteTemplateDescPart2: '"? This action cannot be undone.',
    yesDeleteBtn: 'Yes, Delete',
    changesSavedToast: 'Changes saved successfully',
    editBtn: 'Edit',
    templateNameExists: 'This template name already exists. Please choose a different name.',
  }
};



// Deprecated: Use API instead
export const getTemplates = (lang: Language): Template[] => {
  return [];
};

export const MOCK_TEMPLATES: Template[] = [];
export const MOCK_DOSSIERS: Dossier[] = [];

export const MOCK_SECTIONS: DocumentSection[] = [
  {
    id: 'sec1',
    title: 'Partijen',
    content: 'DE ONDERGETEKENDEN:\n\n1. De heer [placeholder:seller_firstname] [placeholder:seller_lastname], geboren te [placeholder:seller_birthplace] op [placeholder:seller_birthdate], wonende te [placeholder:seller_address]. Hierna gezamenlijk genoemd "de verkoper".\n\n2. De heer [placeholder:buyer1_firstname] [placeholder:buyer1_lastname], geboren te [placeholder:buyer1_birthplace] op [placeholder:buyer1_birthdate], en zijn echtgenote mevrouw [placeholder:buyer2_firstname] [placeholder:buyer2_lastname], geboren te [placeholder:buyer2_birthplace] op [placeholder:buyer2_birthdate], samenwonende te [placeholder:buyers_address]. Gehuwd onder het beheer van de scheiding van goederen met beperkte gemeenschap. Hierna gezamenlijk genoemd "de koper".',
    isApproved: false,
    placeholders: [
      { id: 'seller_firstname', label: 'Voornaam verkoper', currentValue: 'Jeu Alfons', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'seller_lastname', label: 'Achternaam verkoper', currentValue: 'LENS', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'seller_birthplace', label: 'Geboorteplaats verkoper', currentValue: 'Onze-Lieve-Vrouw-Waver', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'seller_birthdate', label: 'Geboortedatum verkoper', currentValue: '17 juni 1931', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'seller_address', label: 'Adres verkoper', currentValue: 'Schaben, Wordenfreinstienen 4/2', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer1_firstname', label: 'Voornaam koper 1', currentValue: 'Stéphane Joseph Henri', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer1_lastname', label: 'Achternaam koper 1', currentValue: 'VERELST', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer1_birthplace', label: 'Geboorteplaats koper 1', currentValue: 'Mechelen', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer1_birthdate', label: 'Geboortedatum koper 1', currentValue: '16 augustus 1964', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer2_firstname', label: 'Voornaam koper 2', currentValue: 'An Maria Walter', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer2_lastname', label: 'Achternaam koper 2', currentValue: 'VAN AS', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer2_birthplace', label: 'Geboorteplaats koper 2', currentValue: 'Leuven', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyer2_birthdate', label: 'Geboortedatum koper 2', currentValue: '21 januari 1976', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
      { id: 'buyers_address', label: 'Adres kopers', currentValue: 'Sint-Katelijne-Waver (Onze-Lieve-Vrouw-Waver), Waverlaan 2', sourceDoc: 'huis.docx', sourcePage: 1, confidence: 'High', isApproved: false },
    ]
  },
  {
    id: 'sec2',
    title: 'Verkoopsvoorwerp',
    content: 'ZIJN OVEREENGEKOMEN WAT VOLGT:\n\nDe verkoper verklaart -- onder cumulatieve vervulling van nagemelde opschortende voorwaarde -- te verkopen, af te staan en over te dragen aan de koper, die aanvaardt -- ieder tot beloop van de onverdeelde helft in volle eigendom -- het hierna omschreven onroerend goed en dit onder de gewone waarborgen van daad en van recht, en voor vrij, zuiver en onbelast van alle voorrechten, hypotheken, bezwarende overschrijvingen of kantmeldingen en alle welkdanige lasten of schulden.',
    isApproved: false,
    placeholders: []
  },
  {
    id: 'sec3',
    title: 'Beschrijving van het goed',
    content: 'BESCHRIJVING VAN HET GOED:\n\nGemeente [placeholder:property_municipality] -- [placeholder:property_section], voorheen [placeholder:property_former_name]: Een perceel landbouwgrond met bunker, gelegen aan de [placeholder:property_street], gekadastreerd sectie [placeholder:cadastral_section] nr. [placeholder:cadastral_number], groot volgens titel [placeholder:property_size]. Hierna kortweg omschreven als "het goed" of "voorschreven goed".',
    isApproved: true,
    placeholders: [
      { id: 'property_municipality', label: 'Gemeente eigendom', currentValue: 'SINT-KATELIJNE-WAVER', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'property_section', label: 'Afdeling', currentValue: '3e afdeling', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'property_former_name', label: 'Vroegere naam', currentValue: 'ONZE-LIEVE-VROUW-WAVER', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'property_street', label: 'Straat eigendom', currentValue: 'Kegelslei', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'cadastral_section', label: 'Kadastrale sectie', currentValue: 'C', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'cadastral_number', label: 'Kadastraal nummer', currentValue: '98', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
      { id: 'property_size', label: 'Grootte eigendom', currentValue: 'één hectare vier are drieëndertig centiare (01 ha 04 a 33 ca)', sourceDoc: 'huis.docx', sourcePage: 2, confidence: 'High', isApproved: true },
    ]
  },
  {
    id: 'sec4',
    title: 'Voorwaarden: Toestand & Erfdienstbaarheden',
    content: 'VOORWAARDEN:\n\n1° Toestand -- Erfdienstbaarheden: Het goed wordt verkocht in de staat waarin het zich thans bevindt en onder meer:\n\n- zonder waarborg van maat en oppervlakte, al bedragen de verschillen één/twintigste of meer;\n- met alle voor- en nadelige erfdienstbaarheden;\n- met alle zichtbare en verborgen gebreken, zonder vrijwaring dezer;\n- met alle gemeenschappen.\n\nDe verkoper verklaart geen weet te hebben van het bestaan van erfdienstbaarheden en er zelf geen te hebben toegestaan.',
    isApproved: true,
    placeholders: []
  },
  {
    id: 'sec5',
    title: 'Voorwaarden: Eigendom, Bezit & Genot',
    content: '2° Eigendom -- Bezit -- Genot:\n\nDe koper treedt in het recht van eigendom van het voorschreven goed te rekenen vanaf de ondertekening van de notariële koop-verkoopakte en zal er ook te rekenen vanaf dan alle openbare lasten, gemeentelijke en andere belastingen en taksen van dragen en betalen. Niet-vervallen annuïteiten van verhaalbelastingen en andere gemeentelijke taksen of belastingen zijn voor rekening van de koper vanaf zelfde datum.\n\nDe verkoper verklaart dat er naar zijn weten thans geen verhaalbelastingen verschuldigd zijn noch betekend werden.\n\nDe verkoper verklaart tevens dat het goed, noch geheel noch gedeeltelijk, is onderworpen aan het wettelijk recht van voorkoop ingesteld door de wet op de landpacht.\n\nDe koper zal het genot hebben van voorschreven onroerend goed door de vrije beschikking en effectieve inbezitname vanaf de ondertekening van de notariële koop-verkoopakte en de volledige betaling van de verkoopprijs.',
    isApproved: false,
    placeholders: []
  },
  {
    id: 'sec6',
    title: 'Voorwaarden: Kosten & Stedenbouw',
    content: '3° Kosten:\n\nAlle kosten, rechten en erelonen waartoe deze verkoop kan aanleiding geven, zijn ten laste van de koper, evenals de eventuele opmetingskosten.\n\n4° Stedenbouw:\n\nIn geval van bouwen zal de koper zich moeten onderwerpen aan de beslissingen en reglementen van de bevoegde instanties.\n\nOm te voldoen aan de voorschriften van het "decreet houdende de organisatie van de ruimtelijke ordening" wordt er verklaard door de verkoper dat voor het niet-bebouwde gedeelte geen bouw-, verkavelings- en stedenbouwkundige vergunning werd afgeleverd.\n\nHet bij deze verkochte goed is volgens het gewestplan [placeholder:zoning_plan] gelegen in het [placeholder:zoning_designation] bestemd voor de landbouw.',
    isApproved: false,
    placeholders: [
      { id: 'zoning_plan', label: 'Gewestplan', currentValue: 'Mechelen', sourceDoc: 'huis.docx', sourcePage: 4, confidence: 'High', isApproved: false },
      { id: 'zoning_designation', label: 'Bestemming', currentValue: 'agrarisch gebied', sourceDoc: 'huis.docx', sourcePage: 4, confidence: 'High', isApproved: false },
    ]
  },
  {
    id: 'sec7',
    title: 'Voorwaarden: Bodem & Bescherming',
    content: '5° Verklaring inzake de bodemtoestand:\n\na) De verkoper verklaart dat er op de grond, die het voorwerp is van onderhavige akte, bij zijn weten geen inrichting gevestigd is of was, of geen activiteit wordt of werd uitgeoefend die opgenomen is in de lijst van inrichtingen en activiteiten die bodemverontreiniging kunnen veroorzaken, zoals bedoeld in artikel 3, §1, van het Bodemsaneringsdecreet.\n\nb) De verkoper verklaart met betrekking tot het verkochte goed geen weet te hebben van bodemverontreiniging die schade kan berokkenen aan de koper of aan derden, of die aanleiding kan geven tot een saneringsverplichting, tot gebruiksbeperkingen of tot andere maatregelen die de overheid in dit verband kan opleggen.\n\n6° Verklaring niet-bescherming:\n\nIn uitvoering van het decreet van 16 april 1996 inzake de bescherming van landschappen, verklaart de verkoper dat het bij deze verkochte goed niet gelegen is binnen een voorlopig beschermd landschap.\n\nIn uitvoering van het decreet van 3 maart 1976 verklaart de verkoper dat het goed niet opgenomen is in een lijst, noch voorontwerp of ontwerp van lijst van de voor bescherming vatbare monumenten, stads- en dorpsgezichten.',
    isApproved: true,
    placeholders: []
  },
  {
    id: 'sec8',
    title: 'Verkoopprijs',
    content: 'VERKOOPPRIJS:\n\nDeze verkoping is gedaan en aanvaard voor en mits de prijs van [placeholder:sale_price_words] ([placeholder:sale_price_amount]).\n\nDe koper verbindt zich ertoe binnen de acht dagen vanaf heden als waarborg voor de stipte uitvoering van zijn verplichtingen een bedrag van [placeholder:deposit_amount_words] ([placeholder:deposit_amount]) te storten op de bankrekeningnummer [placeholder:notary_account] van nagenoemde notaris [placeholder:notary_name]. De notaris die deze gelden in bewaring krijgt, plaatst ze op een bijzondere rekening die hij opent op naam van de koper tot bij de ondertekening van de notariële koop-verkoopakte.\n\nHet saldo van de verkoopprijs verbindt de koper zich te betalen bij de ondertekening van de notariële koop-verkoopakte.',
    isApproved: false,
    placeholders: [
      { id: 'sale_price_words', label: 'Verkoopprijs (woorden)', currentValue: 'VIERENTWINTIGDUIZEND VIJFHONDERD EURO', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
      { id: 'sale_price_amount', label: 'Verkoopprijs (cijfers)', currentValue: '24.500,00 EUR', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
      { id: 'deposit_amount_words', label: 'Waarborgbedrag (woorden)', currentValue: 'TWEEDUIZEND VIERHONDERDVIJFTIG EURO', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
      { id: 'deposit_amount', label: 'Waarborgbedrag (cijfers)', currentValue: '2.450,00 EUR', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
      { id: 'notary_account', label: 'Rekeningnummer notaris', currentValue: '230-0122700-15', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
      { id: 'notary_name', label: 'Naam notaris', currentValue: 'André Costa', sourceDoc: 'huis.docx', sourcePage: 5, confidence: 'High', isApproved: false },
    ]
  },
  {
    id: 'sec9',
    title: 'Sancties bij niet-naleving',
    content: 'Ingeval van vertraging van de betaling zal de koper een verwijlvergoeding verschuldigd zijn aan de verkoper van tien frank ten honderd (10 %) \'s jaars op de nog verschuldigde koopprijs, behoudens wanneer deze vertraging te wijten is aan de verkoper. Deze verwijlvergoeding wordt berekend per dag vertraging en voor een jaar worden 365 dagen gerekend.\n\nIngeval van niet-naleving door één van de partijen van de bij deze aangegane verbintenissen en na ingebrekestelling bij aangetekend schrijven of deurwaardersexploot, welk zonder gevolg gelaten werd gedurende een periode van vijftien dagen, zal deze verkoping van rechtswege ontbonden zijn. In dit geval zal een som gelijk aan tien ten honderd van de verkoopprijs aan de niet-ingebreke gebleven partij toekomen ten titel van schadevergoeding.\n\nPartijen behouden zich nochtans het recht voor de gedwongen uitvoering van deze overeenkomst te vervolgen.',
    isApproved: true,
    placeholders: []
  },
  {
    id: 'sec10',
    title: 'Notariële Akte',
    content: 'NOTARIËLE AKTE:\n\nPartijen, die ervan kennis dragen dat ieder van hen het recht heeft zijn eigen notaris te kiezen -- zonder verhoging van kosten --, stellen beiden aan notaris [placeholder:notary_fullname] te [placeholder:notary_address].\n\nDe notariële koop-verkoopakte dient verleden te worden op voorstel van de instrumenterende notaris binnen de drie maand vanaf de vervulling van nagemelde opschortende voorwaarden.',
    isApproved: false,
    placeholders: [
      { id: 'notary_fullname', label: 'Volledige naam notaris', currentValue: 'André Costa', sourceDoc: 'huis.docx', sourcePage: 6, confidence: 'High', isApproved: false },
      { id: 'notary_address', label: 'Adres notaris', currentValue: '2861 Onze-Lieve-Vrouw-Waver, Dijk 34', sourceDoc: 'huis.docx', sourcePage: 6, confidence: 'High', isApproved: false },
    ]
  },
  {
    id: 'sec11',
    title: 'Opschortende Voorwaarden',
    content: 'OPSCHORTENDE VOORWAARDEN:\n\nOm te voldoen aan artikel 36 van het Vlaams Bodemsaneringsdecreet komen partijen overeen dat deze verkoop wordt gedaan onder de opschortende voorwaarde dat voor het bij deze verkochte goed door de Openbare Afvalstoffenmaatschappij van het Vlaams Gewest (OVAM) een bodemattest wordt afgeleverd waaruit blijkt:\n\n- hetzij dat voor het betrokken goed geen gegevens beschikbaar zijn;\n- hetzij dat voor het betrokken goed geen bodemverontreiniging werd vastgesteld die de bodemsaneringsnormen overschrijdt of dreigt te overschrijden, of die een ernstige bedreiging vormt.\n\nDe verkoper verbind zich ertoe dit bodemattest zonder uitstel aan te vragen en de inhoud ervan mee te delen aan de koper binnen de maand te rekenen vanaf heden.',
    isApproved: true,
    placeholders: []
  },
  {
    id: 'sec12',
    title: 'Verzekering',
    content: 'Verzekering in geval van overlijden bij ongeval van de koper:\n\nDe koper erkent dat de notaris die de verkoopovereenkomst heeft opgesteld en waarvan de naam voorkomt, hem op de hoogte gebracht heeft van een ongevallenverzekering onderschreven bij de C.V.B.A. "Verzekeringen van het Notariaat" ingevolge een polis op naam van de notaris en waarvan de hoofdkenmerken hierna weergegeven worden:\n\n- de verzekering is kosteloos voor de koper;\n- verzekerd risico: overlijden door ongeval;\n- verzekerde personen: kopers natuurlijke personen;\n- duur van de dekking: vanaf het ondertekenen van de verkoopovereenkomst tot aan de ondertekening van de authentieke akte van aankoop met een maximumduur van vier maanden na ondertekening van de verkoopovereenkomst.',
    isApproved: false,
    placeholders: []
  },
  {
    id: 'sec13',
    title: 'Ondertekening',
    content: 'Opgemaakt in drie exemplaren, waarvan elke partij verklaart minstens één exemplaar te hebben ontvangen, te [placeholder:signing_location] op [placeholder:signing_date].\n\nGelezen en goedgekeurd [handtekening verkoper]\nGelezen en goedgekeurd [handtekening koper 1]\nGelezen en goedgekeurd [handtekening koper 2]',
    isApproved: false,
    placeholders: [
      { id: 'signing_location', label: 'Plaats ondertekening', currentValue: 'Sint-Katelijne-Waver (Onze-Lieve-Vrouw-Waver)', sourceDoc: 'huis.docx', sourcePage: 8, confidence: 'High', isApproved: false },
      { id: 'signing_date', label: 'Datum ondertekening', currentValue: '26 februari 2003', sourceDoc: 'huis.docx', sourcePage: 8, confidence: 'High', isApproved: false },
    ]
  }
];

export const HOUSE_EXTRACTION_SECTIONS: DocumentSection[] = MOCK_SECTIONS.map(section => ({
  ...section,
  isApproved: false,
  placeholders: section.placeholders.map(p => ({
    ...p,
    currentValue: '',
    sourceDoc: '',
    sourcePage: 0,
    isApproved: false,
    confidence: 'Low'
  }))
}));

